import { shadcnPlugin } from "./plugins/shadcn-ui";

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  themes: {
    colors: {
      stone: {
        50: "var(--novel-stone-50)",
        100: "var(--novel-stone-100)",
        200: "var(--novel-stone-200)",
        300: "var(--novel-stone-300)",
        400: "var(--novel-stone-400)",
        500: "var(--novel-stone-500)",
        600: "var(--novel-stone-600)",
        700: "var(--novel-stone-700)",
        800: "var(--novel-stone-800)",
        900: "var(--novel-stone-900)",
      },
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("daisyui"),
    require("tailwindcss-animate"),
  ],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ],
  },
};
